// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdjCuaiUTY3lOZel0eDeVOIB8IXenKr2k',
    appId: '1:160391890058:web:8aa5da5365cefb17efd973',
    messagingSenderId: '160391890058',
    projectId: 'research-pal-810ce',
    authDomain: 'research-pal-810ce.firebaseapp.com',
    storageBucket: 'research-pal-810ce.firebasestorage.app',
    measurementId: 'G-CS95YN73HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCENTOxRQlZkzlhFgst7sjx3Xo8oyx7RIU',
    appId: '1:160391890058:android:7e6d1c46fda6ad65efd973',
    messagingSenderId: '160391890058',
    projectId: 'research-pal-810ce',
    storageBucket: 'research-pal-810ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxvsqqQreJW79bg3E7XfD0pb41Pd0zFNs',
    appId: '1:160391890058:ios:052495ac886f6c25efd973',
    messagingSenderId: '160391890058',
    projectId: 'research-pal-810ce',
    storageBucket: 'research-pal-810ce.firebasestorage.app',
    iosBundleId: 'com.example.researchMemo',
  );
}
